remote:
  real:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/multi-agyw
  naomi:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-data-orderly
  naomi2:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-orderly-naomi2
  malawi:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/mwi-hiv-orderly

fields:
  requester:
    required: false
  author:
    required: false

global_resources:
  global
